# Generated by Django 5.0.7 on 2024-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "ifsc",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("bank_id", models.IntegerField()),
                ("branch", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
            ],
        ),
    ]
